### ISSUE TITLE
Computed property is misleading

### ISSUE THREAD

**Issue by cupcakearmy** [matschik/component-party#61]
Hi, the project is amazing! Love it!

A note on the computed (https://component-party.dev/#computed-state) example.
The correct equivalent is using `useMemo` because in svelte the computed value only depends on the variables that are read in the statement, while in `react` it's recomputed on each rendern, no matter what. So I think the example should use `useMemo`, maybe add a second variable to show this, or a note.

**Comment by matschik** [comment]
You are totally right !

It's exactly what I did in the first place using `useMemo`.
But since it takes less character for the same result, some React devs wanted to remove `useMemo` haha
I was thinking creating `Computed state with memoization`.

Well I think we can't replicate the exact same behavior for each framework. 
Component Party is not meant to be perfect because it's near impossible.

**Comment by cupcakearmy** [comment]
Nice that we are on the same page ❤️ 
Adding `Computed state with memoization` directly after the `computed state` sounds like the way to go. 
That way the react one-liner fanboys are happy, but we also get the "truth" out there 😉

I can do a PR next week if you like to :)
